// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjzujrwbfwcxdnjnuhws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqenVqcndiZndjeGRuam51aHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyNjAxNTEsImV4cCI6MjA1NjgzNjE1MX0.kSX3fh3lJMgw28Q4cClMzDOO3sDjbXyFOQ5fKx6p6E8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);